name: wt_firepod
description: Package the integrates Firebase and Riverpod functionality.
version: 1.0.0+1
publish_to: 'none'
homepage: https://github.com/tmcmaster/wt_firepod

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.29.2'

dependencies:
  crypto: ^3.0.6
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  firebase_crashlytics: ^4.1.3
  firebase_database: ^11.1.4
  firebase_storage: ^12.3.3
  firebase_ui_auth: ^1.16.0
  firebase_ui_localizations: ^1.13.0
  firebase_ui_oauth_apple: ^1.3.0
  firebase_ui_oauth_google: ^1.4.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.4.1
  flutter_inappwebview:
#    git:
#      url: git@github.com:tmcmaster/flutter_inappwebview.git
#      path: flutter_inappwebview
  flutter_localization: ^0.2.2
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.4
  go_router: ^10.2.0
  google_sign_in: ^6.2.1
  logger: ^2.4.0
  shared_preferences: ^2.3.2
  sign_in_with_apple: ^6.1.3
  uuid: ^4.5.0

  wt_action_button:
    git:
      url: git@github.com:tmcmaster/wt_action_button.git
  wt_app_scaffold:
    git:
      url: git@github.com:tmcmaster/wt_app_scaffold.git
  wt_logging:
    git:
      url: git@github.com:tmcmaster/wt_logging.git
  wt_models:
    git:
      url: git@github.com:tmcmaster/wt_models.git
  wt_settings:
    git:
      url: git@github.com:tmcmaster/wt_settings.git

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  wt_action_button:
    path: ../wt_action_button
  wt_app_scaffold:
    path: ../wt_app_scaffold
  wt_logging:
    path: ../wt_logging
  wt_models:
    path: ../wt_models
  wt_settings:
    path: ../wt_settings

flutter:
  uses-material-design: true
