name: wt_firepod
description: Package the integrates Firebase and Riverpod functionality.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/tmcmaster/wt_firepod

environment:
  sdk: '>=3.0.5 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  check: flutter analyze
  outdated: dart pub outdated --show-all
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs

dependencies:
  cloud_functions:
  crypto:
  firebase_auth:
  firebase_core:
  firebase_database:
  firebase_remote_config:
  flutter:
    sdk: flutter
  flutter_animated_dialog:
  flutter_form_builder:
  flutter_hooks:
  flutter_riverpod:
  font_awesome_flutter:
  form_builder_validators:
  freezed_annotation:
  google_sign_in:
  hooks_riverpod:
  logger:
  riverpod:
  shared_preferences:
  sign_in_with_apple:
  uuid:
  wt_logging:
    git:
      url: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git: https://github.com/tmcmaster/wt_models.git
  wt_settings:
    git:
      url: https://github.com/tmcmaster/wt_settings.git

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  wt_models:
#    path: ../wt_models
#  wt_settings:
#    path: ../wt_settings
#  wt_logging:
#    path: ../wt_logging

flutter:
