name: wt_firepod
description: Package the integrates Firebase and Riverpod functionality.
version: 0.0.1
publish_to: 'none'
homepage: https://github.com/tmcmaster/wt_firepod

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  wt_models:
    git: git@github.com:tmcmaster/wt_models.git
  wt_settings:
    git: git@github.com:tmcmaster/wt_settings.git
  wt_logging:
    git: git@github.com:tmcmaster/wt_logging.git
  shared_preferences:
  crypto:
  logger:
  riverpod:
  freezed_annotation:
  font_awesome_flutter:
  hooks_riverpod:
  flutter_hooks:
  flutter_riverpod:
  firebase_core:
  firebase_auth:
  firebase_database:
  firebase_remote_config:
  cloud_functions:
  flutter_form_builder:
  form_builder_validators:
  flutter_animated_dialog:
  uuid:
  google_sign_in:
  sign_in_with_apple:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

dependency_overrides:
#  wt_models:
#    path: ../wt_models
#  wt_settings:
#    path: ../wt_settings
#  wt_logging:
#    path: ../wt_logging
