name: wt_firepod
description: Package the integrates Firebase and Riverpod functionality.
version: 1.0.0+1
publish_to: 'none'
homepage: https://github.com/tmcmaster/wt_firepod

environment:
  sdk: '>=3.0.5 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  check: flutter analyze
  outdated: dart pub outdated --show-all
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs

dependencies:
  cloud_functions: ^4.3.4
  crypto: ^3.0.3
  firebase_auth: ^4.7.0
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  firebase_remote_config: ^4.2.4
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_form_builder: ^9.0.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.1.4
  logger: ^1.4.0
  shared_preferences: ^2.2.0
  sign_in_with_apple: ^5.0.0
  uuid: ^3.0.7
  wt_logging:
    git:
      url: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git: https://github.com/tmcmaster/wt_models.git
  wt_settings:
    git:
      url: https://github.com/tmcmaster/wt_settings.git

dev_dependencies:
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  wt_models:
#    path: ../wt_models
#  wt_settings:
#    path: ../wt_settings
#  wt_logging:
#    path: ../wt_logging

flutter:
  uses-material-design: true
