name: wt_firepod_examples
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter:
  freezed:
  freezed_annotation:
  riverpod: ^2.0.2
  flutter_riverpod: ^2.0.2
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  firebase_database: ^10.0.3
  firebase_remote_config: ^3.0.3
  cloud_functions: ^4.0.3
  firebase_ui_auth: ^1.0.3
  firebase_ui_oauth_google: ^1.0.3
  firebase_ui_oauth_apple: ^1.0.3
  firebase_ui_oauth_facebook: ^1.0.3
  firebase_ui_oauth_twitter: ^1.0.3
  firebase_ui_database: ^1.0.3
  wt_app_scaffold:
    git: git@github.com:tmcmaster/wt-app-scaffold.git
  wt_firepod:
    git: git@github.com:tmcmaster/wt_firepod.git
  wt_action_button:
    git: git@github.com:tmcmaster/wt_action_button.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  freezed:
  json_serializable:
flutter:
  uses-material-design: true
  assets:
    - assets/
