name: wt_firepod_examples
description: Examples project for the wt_firepod package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Scripts to be run with rps
scripts:
  init: flutter pub get
  clean: flutter clean
  refresh: flutter clean; flutter pub get
  test: flutter test
  check: flutter analyze
  outdated: dart pub outdated --show-all
  freezed:
    build: dart run build_runner build --delete-conflicting-outputs
  macos:
    init: flutter create --platforms=macos .
    build: flutter build macos --release
    run: flutter run -t lib/main_widgetbook.dart -d MacOS
    configure: open macos/Runner.xcworkspace
    fix: (cd macos; rm Podfile.lock; gem pristine ffi --version 1.15.5; pod install --repo-update)

dependencies:
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_database: ^10.2.4
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_form_builder: ^9.1.0
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  form_builder_validators: ^9.0.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  riverpod: ^2.3.6
  wt_action_button:
    git: https://github.com/tmcmaster/wt_action_button.git
  wt_firepod:
    git: https://github.com/tmcmaster/wt_firepod.git
  wt_logging:
    git: https://github.com/tmcmaster/wt_logging.git
  wt_models:
    git: https://github.com/tmcmaster/wt_models.git

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  wt_firepod:
    path: ..
#  wt_app_scaffold:
#    path: ../../wt_app_scaffold
  #  wt_models:
  #    path: ../wt_models
  #  wt_settings:
  #    path: ../wt_settings
#  wt_logging:
#    path: ../../wt_logging