name: wt_firepod_examples
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  font_awesome_flutter:
  freezed:
  freezed_annotation:
  riverpod:
  flutter_riverpod:
  firebase_core:
  firebase_auth:
  firebase_database:
  firebase_remote_config:
  cloud_functions:
  flutter_form_builder:
  form_builder_validators:
  flutter_animated_dialog:
  logger:
  wt_firepod:
    git: git@github.com:tmcmaster/wt_firepod.git
  wt_action_button:
    git: git@github.com:tmcmaster/wt_action_button.git
  wt_models:
    git: git@github.com:tmcmaster/wt_models.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  freezed:
  json_serializable:
flutter:
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  wt_firepod:
    path: ..
